language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - DC_VERSION=2.1.*
  - DC_VERSION=2.2.*
  - DC_VERSION=2.3.*
  - DC_VERSION=2.4.*

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require doctrine/orm:${DC_VERSION} doctrine/dbal:${DC_VERSION} doctrine/common:${DC_VERSION}
  - composer install --dev

script:
  - phpunit

notifications:
  email:
    - lstrojny@php.net
