language: php

sudo: false

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - DC_VERSION=2.1.*
  - DC_VERSION=2.2.*
  - DC_VERSION=2.3.*
  - DC_VERSION=2.4.*
  - DC_VERSION=2.5.*

before_script:
  - composer require doctrine/orm:${DC_VERSION} doctrine/dbal:${DC_VERSION} doctrine/common:${DC_VERSION}
  - composer install

script:
  - phpunit
