language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DC_VERSION=2.1.*
  - DC_VERSION=2.2.*
  - DC_VERSION=2.3.*
  - DC_VERSION=2.4.*

before_script:
  - composer require doctrine/orm:${DC_VERSION} doctrine/dbal:${DC_VERSION} doctrine/common:${DC_VERSION}
  - composer install

script:
  - phpunit
